development:
  adapter: sqlite3
  encoding: utf8
  database: db/developement.sqlite3
  port: 5000
  host: localhost

test:
  adapter: sqlite3
  encoding: utf8
  port: 5000
  database: db/test.sqlite3
  host: localhost

production:
 adapter: pg
 encoding: utf8
 pool: 5
 url: postgres://xubvjnzgvpbdys:UAAFR1x7205FjA5U3aelRMXgRC@ec2-54-197-241-97.compute-1.amazonaws.com:5432/d1r3t8suhoj30m