development:
  adapter: postgresql
  encoding: utf8
  database: dcienh2mprnsup
  username: mmmjoutehpejsv
  port: 5432
  password: 4Wt_GUQNDrEdInuABRJGq8ezn4
  host: ec2-79-125-26-111.eu-west-1.compute.amazonaws.com

test:
  adapter: postgresql
  encoding: utf8
  database: dcienh2mprnsup
  username: mmmjoutehpejsv
  port: 5432
  password: 4Wt_GUQNDrEdInuABRJGq8ezn4
  host: ec2-79-125-26-111.eu-west-1.compute.amazonaws.com

production:
  adapter: postgresql
  encoding: utf8
  database: dcienh2mprnsup
  username: mmmjoutehpejsv
  port: 5432
  password: 4Wt_GUQNDrEdInuABRJGq8ezn4
  host: ec2-79-125-26-111.eu-west-1.compute.amazonaws.com