default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
 adapter: pg
 encoding: utf8
 pool: 5
 port: 5432
 url: postgres://xubvjnzgvpbdys:UAAFR1x7205FjA5U3aelRMXgRC@ec2-54-197-241-97.compute-1.amazonaws.com:5432/d1r3t8suhoj30m