development:
  adapter: sqlite3
  encoding: utf8
  database: db/developement.sqlite3
  port: 5000
  host: localhost

test:
  adapter: sqlite3
  encoding: utf8
  port: 5000
  database: db/test.sqlite3
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  port: 5432
  url: mmmjoutehpejsv:4Wt_GUQNDrEdInuABRJGq8ezn4@ec2-79-125-26-111.eu-west-1.compute.amazonaws.com:5432/dcienh2mprnsup