default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
 adapter: pg
 encoding: utf8
 pool: 5
 port: 5432
 url:  postgres://ywnrbkdxelcdxf:GHHo-8QRMgKnLFDrSOlTyq4maP@ec2-54-163-239-102.compute-1.amazonaws.com:5432/deo77kgvqrrh39